services:
  backend:
    container_name: yfinance-client
    build:
      context: yfinance-client
    volumes:
      - ./yfinance-client:/home/app/
      - ./config.json:/home/config.json
    ports:
      - 4040:4040
      # - 9998:9998
      
    
    entrypoint: /home/app/entrypoint.sh

  frontend:
    container_name: dashboard
    build:
      context: dashboard
    volumes:
      - ./dashboard:/home/app/
      - ./config.json:/home/config.json
      - /var/container/some.sock:/var/run/some.sock
    ports:
      - 8050:8050
    entrypoint: /home/app/entrypoint.sh
