services:
  spark-master:
    container_name: spark-master
    build: .
    volumes:
      - './src/:/opt/app/src'
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      - MASTER_IP=${MASTER_IP}
    entrypoint: ["sh", "/opt/app/entrypoints/master-entrypoint.sh"]
